apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - postgres.yaml
  - oneapi.yaml
  - networkpolicy.yaml

secretGenerator:
  - name: oneapi-secrets
    literals:
      - ONEAPI_ADMIN_USER=admin
      - ONEAPI_ADMIN_PASS=admin
      - ONEAPI_API_KEYS=dev-key
      - ONEAPI_UPSTREAMS=REPLACE_ME
      - POSTGRES_USER=oneapi
      - POSTGRES_PASSWORD=oneapi
      - POSTGRES_DB=oneapi
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://oneapi:oneapi@postgres:5432/oneapi

generatorOptions:
  disableNameSuffixHash: true
